### ISSUE TITLE
VerifyError: JNI sees Object instead of Try Monad

### ISSUE THREAD

**Issue by micotom** [arrow-kt/arrow-core#18]
With switching from generified Try.Failure to Try.Failure\<Nothing\> by default (PR: arrow-kt/arrow#971 ), a strange issue pops up:

```kotlin
fun causesVerifyError(): Try<Boolean> {
    val b = someBooleanFunction()
    return Try.Success(b)
        .map {
            !it
        }
}
```

causes

```java
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    MainKt.causesVerifyError()Larrow/core/Try; @88: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'arrow/core/Try' (from method signature)
  Current Frame:
    bci: @88
    flags: { }
    locals: { integer, 'arrow/core/Try$Success', 'arrow/core/Try$Success', 'arrow/core/Try$Success' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: b800 223b bb00 2459 1ab8 002a b700 2e4c
    0x0000010: 002b 4d2c 4e2d c100 3099 0007 2ca7 0039
    0x0000020: 2cb6 0034 3a04 1904 c000 26b6 0037 3605
    0x0000030: 1505 9a00 0704 a700 0403 b800 2a3a 0e19
    0x0000040: 0e3a 0fbb 0024 5919 0fb7 002e c000 393a
    0x0000050: 0719 07c0 003b 0000 b0                 
  Stackmap Table:
    full_frame(@32,{Integer,Object[#36],Object[#36],Object[#36]},{})
    append_frame(@57,Object[#4],Integer)
    same_locals_1_stack_item_frame(@58,Integer)
    full_frame(@86,{Integer,Object[#36],Object[#36],Object[#36]},{Object[#4]})

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Error: A JNI error has occurred, please check your installation and try again
```

Whereas following workaround works:

```kotlin
fun causesVerifyError(): Try<Boolean> =
    with(someBooleanFunction()) {
        Try.Success(this)
            .map {
                !it
            }
    }
```

**Kotlin version**: 1.3.11
**JDK Target**: 1.8
**JDK**: 1.8.0_181

**Comment by aballano** [comment]
The issue seems to be fixed in the Kotlin side, so I'll be closing this one, feel free to comment if you still face the problem.
